"""Hook installation (SRS 4.4.1.1).

The hook is generated rather than copied, because it must embed two absolute
paths resolved at install time:

  * the interpreter -- hooks run in Git's environment, which does not inherit
    the developer's activated virtualenv, so `python` on PATH is usually the
    wrong one (or absent);
  * the package root -- RepoHealth is run from a clone rather than installed,
    so PYTHONPATH has to point at it.

Git for Windows ships its own `sh`, and runs `.git/hooks/pre-commit` through
it, so a single POSIX script serves both platforms. The PowerShell variant is
written alongside for developers who want to invoke the check by hand.
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

HOOK_MARKER = "# >>> repohealth gatekeeper >>>"

SH_TEMPLATE = """#!/bin/sh
{marker}
# Generated by `repohealth init`. Delete this file to uninstall.
# Bypass once with:  git commit --no-verify
PYTHONPATH="{pkg_root}" "{python}" -m repohealth.cli check --staged
status=$?
if [ $status -ne 0 ]; then
    exit $status
fi
exit 0
"""

PS1_TEMPLATE = """# {marker}
# Manual invocation of the RepoHealth gatekeeper.
#   .\\pre-commit.ps1
$env:PYTHONPATH = "{pkg_root}"
& "{python}" -m repohealth.cli check --staged
exit $LASTEXITCODE
"""


def _package_root() -> str:
    """Directory that must be on PYTHONPATH for `import repohealth` to work."""
    return str(Path(__file__).resolve().parents[2])


def hooks_dir(repo) -> Path:
    """`.git/hooks`, resolved through git_dir so worktrees work."""
    return Path(repo.git_dir) / "hooks"


def install(repo, force: bool = False) -> tuple[Path, str]:
    """Returns (hook path, action) where action is installed/updated/skipped."""
    hdir = hooks_dir(repo)
    hdir.mkdir(parents=True, exist_ok=True)
    hook = hdir / "pre-commit"

    python = sys.executable or "python3"
    pkg_root = _package_root()

    if hook.exists():
        existing = hook.read_text(encoding="utf-8", errors="replace")
        if HOOK_MARKER in existing:
            action = "updated"
        elif force:
            backup = hdir / "pre-commit.pre-repohealth"
            backup.write_text(existing, encoding="utf-8")
            action = "replaced"
        else:
            return hook, "skipped"
    else:
        action = "installed"

    hook.write_text(
        SH_TEMPLATE.format(
            marker=HOOK_MARKER,
            python=python.replace("\\", "/"),
            pkg_root=pkg_root.replace("\\", "/"),
        ),
        encoding="utf-8",
        newline="\n",  # Git's sh will not run a script with CRLF line endings
    )
    hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    (hdir / "pre-commit.ps1").write_text(
        PS1_TEMPLATE.format(
            marker=HOOK_MARKER,
            python=python,
            pkg_root=pkg_root,
        ),
        encoding="utf-8",
    )

    return hook, action


def ensure_gitignored(repo, db_rel: str) -> bool:
    """Add the analysis database to .gitignore.

    Without this the first commit after `init` sweeps `.repohealth/` into the
    repository, and every developer then fights over a binary SQLite file in
    version control. Returns True if the file was modified.
    """
    root = Path(repo.working_tree_dir)
    entry = db_rel.split("/")[0].rstrip("/") + "/"
    gitignore = root / ".gitignore"

    existing = ""
    if gitignore.exists():
        existing = gitignore.read_text(encoding="utf-8", errors="replace")
        lines = {ln.strip().rstrip("/") for ln in existing.splitlines()}
        if entry.rstrip("/") in lines:
            return False

    prefix = "" if (not existing or existing.endswith("\n")) else "\n"
    with gitignore.open("a", encoding="utf-8") as fh:
        fh.write(f"{prefix}\n# RepoHealth analysis database (local, not shared)\n{entry}\n")
    return True


def uninstall(repo) -> bool:
    hook = hooks_dir(repo) / "pre-commit"
    if not hook.exists():
        return False
    if HOOK_MARKER not in hook.read_text(encoding="utf-8", errors="replace"):
        return False
    hook.unlink()
    backup = hooks_dir(repo) / "pre-commit.pre-repohealth"
    if backup.exists():
        backup.rename(hook)
        hook.chmod(hook.stat().st_mode | stat.S_IXUSR)
    ps1 = hooks_dir(repo) / "pre-commit.ps1"
    if ps1.exists():
        ps1.unlink()
    return True


def status(repo) -> str:
    hook = hooks_dir(repo) / "pre-commit"
    if not hook.exists():
        return "not installed"
    text = hook.read_text(encoding="utf-8", errors="replace")
    if HOOK_MARKER in text:
        return "installed"
    return "a different pre-commit hook is present"
